### ISSUE TITLE
Error with MySQL v5.5

### ISSUE THREAD

**Issue by pipaltree** [jackd248/db-sync-tool#12]
When trying to create a dump on a system with (admittedly way too old) MySQL Version 5.5 the tool is exiting with error message:

`[ERROR] mysqldump: unknown option '--no-tablespaces'`

Would it be possible to provide a fix for this?

Thanks and keep up the amazing work! 👍

**Comment by jackd248** [comment]
With version **v2.5.5** a database version check is implemented and the option '--no-tablespaces' will be ignored for mysql < v5.6.
