### ISSUE TITLE
Cronjob not running

### ISSUE THREAD

**Issue by youssefeladawy** [jackd248/db-sync-tool#15]
Tried to run db-sync-tool as cronjob but it doesnt run at all! 
here's the crontab task > 
19 10 * * * /usr/bin/python3 /usr/local/bin/db_sync_tool --yes --config-file /var/www/html/mconfig.json

**Comment by jackd248** [comment]
Hej there,

have you tried to run the command by your own to see the result? 
```bash
/usr/bin/python3 /usr/local/bin/db_sync_tool --yes --config-file /var/www/html/mconfig.json
```
Otherwise you can define a cronjob log file to see the result of the db-sync-tool:
```bash
19 10 * * * /usr/bin/python3 /usr/local/bin/db_sync_tool --yes --config-file /var/www/html/mconfig.json > /var/www/html/logs/db-sync-tool.log 2>&1
```

Which version of the db-sync-tool do you use?

**Comment by youssefeladawy** [comment]
Hey there. Thanks for your reply 

Yes I tried 
`/usr/bin/python3 /usr/local/bin/db_sync_tool --yes --config-file /var/www/html/mconfig.json
`
and it runs just fine. 

I tried to log it but there is no log file being created and there is also nothing in the syslog which is weird. 

I have other cron tasks running just fine.

**Comment by youssefeladawy** [comment]
Updated it to the latest version (2.9.0) and it works! thank you so much and sorry for bothering you.
