### ISSUE TITLE
Cancel dump imports dump

### ISSUE THREAD

**Issue by JulianXIMA** [jackd248/db-sync-tool#18]
Are you sure, you want to import the dump file into local database? [Y|n]: n

By pressing "n" the dump file gets imported nevertheless.

**Comment by jackd248** [comment]
Yap, you're absolutly right, the script was just checking the confirmation, but not considering the input.

This was fixed in 2883307ef08a8acc8ce0487d92cee3a8a66cce50 and release v2.10.2
