### ISSUE TITLE
Error when trying to sync two remotes

### ISSUE THREAD

**Issue by pipaltree** [jackd248/db-sync-tool#19]
With version 2.10.4 it seems there has been introduced an issue when syncing two remotes.
When the tool tries to import the dump on the target system there is an error thrown:

> [TARGET][REMOTE] Importing database dump
> [ERROR] ERROR 1045 (28000): Access denied for user 'db_user'@'localhost' (using password: YES)

Could you please check and provide a fix for this?

Thanks in advance!

**Comment by jackd248** [comment]
You're right, there was a copy&paste issue with the last database password fix, so the wrong password was used to import the database dump.
A new version **2.10.5** is provided for solving this issue.
