### ISSUE TITLE
How to sync only the mysql scructure ? --no-data ?

### ISSUE THREAD

**Issue by guimafx** [jackd248/db-sync-tool#22]
Dear Konrad 

Is that possible to SYNC only table structure ? LIKE --no-data ?

Thanks

**Comment by jackd248** [comment]
Hej @guimafx,

I created an option to pass additional options for the mysqldump command.

So e.g.

`db_sync_tool -f file.yaml --additional-mysqldump-options="--no-data"`

Check out new version 2.11.1 for this feature.

Hope this is a useful option for your matter.

**Comment by guimafx** [comment]
Hello, 
When i run --additional-mysqldump-options="--no-data" ... It's making a TRUNCATE table ! 

Is not suppose to Sync Only Table FIELDS ? when passing "--no-data" ?

`db_sync_tool --yes --origin-db-name DBMAIN_NAME --origin-db-host XXX.XXX.XXX.XXX --origin-db-user pingo_fogo --origin-db-password \#XXXXX --target-db-name v3saas1291 --target-db-host XXX.XXX.XXX.XXX --target-db-user pingo_fogo --target-db-password \#XXXXX  --tables cel_recursos_rateio --additional-mysqldump-options="--no-data"
`

I must keep the DATA in table TARGET, and SYNC the field structure. I got no idea how to do it.

Thanks,

**Comment by guimafx** [comment]
IT HAS WORKED !!!

--additional-mysqldump-options="--no-data, -d" 

It sync only scructure and keep the old data....
