### ISSUE TITLE
Empty dump if credentials invalid

### ISSUE THREAD

**Issue by hirnsturm** [jackd248/db-sync-tool#8]
**Current behaviour:**
The sync tool creates an empty database dump if credentials invalid.

**Expected behaviour:**
Throwing exception or abort with exit 1 if database credentials invalid.

**Affected Version:** 
v1.7.2

**Test case:** 
TYPO3 LocalConfiguration.php with invalid database password, dbname or host.

**Comment by jackd248** [comment]
The problem occured only for local commands, the remote command already got a better error handling. I fixed the local command error handling and also (re)provided the "check dump" feature to verify the generated dump file. 
Changes will be released with version **1.8.0**
